Update install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -52,7 +52,7 @@ function install_mlton() {
   (
     echo "∗ Downloading and installing mlton..."
     mkdir -p "${install_path}/bin"
-    curl --silent --location --output "$source_path" -C - "$download_url" || fail "Could not download"
+    curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
     tar -zxf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
     echo "The installation was successful!"
   ) || (
